name: Test Python package using Docker GDAL

on: [push, pull_request]

jobs:
  TestLinux:
    name: GDAL ${{ matrix.container }}
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        container:
          - "osgeo/gdal:ubuntu-small-latest" # python 3.8.5
          - "osgeo/gdal:ubuntu-small-3.2.1"  # python 3.8.2
          - "osgeo/gdal:ubuntu-small-3.1.3"
          - "osgeo/gdal:ubuntu-small-3.0.4"  # python 3.6.9

    container:
      image: ${{ matrix.container }}

    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        run: |
          apt-get update && apt-get install -y python3-pip

      - name: Install Python Dependencies
        run: |
          python3 -m pip install --no-cache-dir -U pip
          python3 -m pip install --no-cache-dir -U wheel
          python3 -m pip install cython==0.29.21 numpy==1.19.5
          python3 -m pip install --no-cache-dir --no-build-isolation -e .[dev,test]

      - name: Print Environment
        run: |
          echo python3 --version
          echo python3 -m pip freeze

      - name: Test with pytest
        run: |
          pytest --cov=pyogrio tests
