name: Docker GDAL Test

on: [push, pull_request]

jobs:
  TestLinux:
    name: GDAL ${{ matrix.container }}
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        container:
          - "osgeo/gdal:ubuntu-small-latest" # python 3.8.5
          - "osgeo/gdal:ubuntu-small-3.2.1" # python 3.8.2
          - "osgeo/gdal:ubuntu-small-3.1.3" # python 3.8.2

    container:
      image: ${{ matrix.container }}

    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        run: |
          apt-get update && apt-get install -y python3-pip

      - name: Install Python Dependencies
        run: |
          python3 -m pip install --no-cache-dir -U pip wheel
          python3 -m pip install --no-cache-dir cython~=0.29
          python3 -m pip install --no-cache-dir --no-build-isolation -e .[dev,test,geopandas]

      - name: Print Environment
        run: |
          echo python3 --version
          echo python3 -m pip freeze

      - name: Test with pytest
        run: |
          pytest --cov=pyogrio --cov-report term-missing pyogrio/tests
