name: Test Python package using Docker GDAL

on: [push, pull_request]

jobs:
  TestLinux:
    runs-on: ubuntu-18.04
    container: osgeo/gdal:ubuntu-small-3.2.1  # python 3.8.2

    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        run: |
          apt-get update && apt-get install -y python3-pip

      - name: Install Python Dependencies
        run: |
          python -m pip install --no-cache-dir -U pip
          python -m pip install --no-cache-dir -U wheel
          python -m pip install --no-cache-dir -e .[dev]

      - name: Print Environment
        run: |
          echo "python --version"
          echo "python -m pip freeze"

      - name: Test with pytest
        run: |
          pytest --cov=pyogrio
